spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_seed?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: zpc920515
    initialization-mode: always
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 100ms
    lettuce:
      pool:
        max-wait: 1ms
        max-active: 8
        min-idle: 0
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.level.org.springframework.boot.autoconfigure: ERROR